# Generated by Django 4.1.2 on 2022-11-02 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customizations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cost', models.TextField()),
                ('type', models.TextField()),
                ('amount', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('name', models.TextField()),
                ('ingredient', models.IntegerField()),
            ],
            options={
                'db_table': 'customizations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Finances',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('orders', models.TextField()),
                ('revenue', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('expenses', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('profit', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('inventory_usage', models.TextField()),
            ],
            options={
                'db_table': 'finances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('stock', models.FloatField()),
                ('ordered', models.FloatField(blank=True, null=True)),
                ('amount_per_unit', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'inventory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('price', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('ingredients', models.TextField()),
                ('size', models.TextField(blank=True, null=True)),
                ('type', models.TextField()),
            ],
            options={
                'db_table': 'menu',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('menu_id', models.BigIntegerField(blank=True, null=True)),
                ('customizations', models.TextField(blank=True, null=True)),
                ('amount', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'order_items',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cashier', models.TextField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('items', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': False,
            },
        ),
    ]
