# Generated by Django 4.1.2 on 2022-11-08 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={"managed": False},
        ),
    ]
