# Generated by Django 4.1.2 on 2022-11-02 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customizations",
            options={},
        ),
        migrations.AlterModelOptions(
            name="finances",
            options={},
        ),
        migrations.AlterModelOptions(
            name="inventory",
            options={},
        ),
        migrations.AlterModelOptions(
            name="menu",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orderitems",
            options={},
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={},
        ),
    ]
