# Generated by Django 4.1.2 on 2022-11-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0002_alter_menu_options"),
    ]

