# Generated by Django 4.1.2 on 2022-11-08 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0003_auto_20221108_2343"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="menu",
            options={},
        ),
    ]
