# Generated by Django 4.1.3 on 2022-11-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_menu_image_asset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image_asset',
        ),
        migrations.AddField(
            model_name='menu',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images'),
        ),
    ]
