# Generated by Django 4.1.3 on 2022-11-09 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0006_remove_menu_image_asset_menu_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AddField(
            model_name='menu',
            name='image_asset',
            field=models.TextField(null=True),
        ),
    ]
