# Generated by Django 4.1.3 on 2022-11-09 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0007_remove_menu_image_menu_image_asset'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='image_asset',
            new_name='image',
        ),
    ]
