# Generated by Django 4.1.2 on 2022-11-09 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0008_rename_image_asset_menu_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="price",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                through="storefront.OrderItem", to="storefront.menu"
            ),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="storefront.order"
            ),
        ),
        migrations.CreateModel(
            name="ItemCustomization",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("amount", models.IntegerField()),
                (
                    "customization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storefront.customization",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="storefront.orderitem",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="customizations",
        ),
        migrations.AddField(
            model_name="orderitem",
            name="customizations",
            field=models.ManyToManyField(
                through="storefront.ItemCustomization", to="storefront.customization"
            ),
        ),
    ]
