# Generated by Django 4.1.2 on 2022-11-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "storefront",
            "0009_remove_order_price_order_items_alter_orderitem_order_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="customization",
            name="name",
            field=models.TextField(default=""),
        ),
    ]
