# Generated by Django 4.1.2 on 2022-11-22 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0010_alter_customization_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="menu_item",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING, to="storefront.menu"
            ),
        ),
    ]
