# Generated by Django 4.1.2 on 2022-11-28 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0013_remove_finance_inventory_usage"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=11),
            preserve_default=False,
        ),
    ]
