# Generated by Django 4.1.3 on 2022-11-28 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0014_menu_description'),
        ('storefront', '0014_orderitem_cost'),
    ]

    operations = [
    ]
