# Generated by Django 4.1.2 on 2022-11-28 16:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0015_merge_0014_menu_description_0014_orderitem_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menu",
            name="description",
            field=models.TextField(default="Lorem"),
        ),
        migrations.CreateModel(
            name="InventoryUsage",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("amount_used", models.FloatField()),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="storefront.inventory",
                    ),
                ),
            ],
        ),
    ]
