# Generated by Django 4.1.3 on 2022-11-28 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0015_merge_0014_menu_description_0014_orderitem_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(default='Lorem'),
        ),
    ]
