# Generated by Django 4.1.3 on 2022-11-30 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0016_alter_menu_description"),
        ("storefront", "0016_alter_menu_description_inventoryusage"),
    ]

    operations = []
