# Generated by Django 4.1.3 on 2022-12-05 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0017_merge_20221130_2302"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryusage",
            name="id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
