# Generated by Django 4.1.3 on 2022-12-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0019_remove_inventoryusage_id_inventoryusage_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=11, null=True
            ),
        ),
    ]
