# Generated by Django 4.1.3 on 2022-12-07 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0020_alter_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="finance",
            name="expenses",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="finance",
            name="profit",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
        migrations.AlterField(
            model_name="finance",
            name="revenue",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11),
        ),
    ]
