# Generated by Django 4.1.3 on 2022-12-07 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0021_alter_finance_expenses_alter_finance_profit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryUsage',
            fields=[
                ('id', models.BigAutoField(primary_key=True)),
                ('date', models.DateField()),
                ('amount_used', models.FloatField()),
                ('item', models.ForeignKey(on_delete=models.DO_NOTHING,
                                           to='storefront.inventory')),
            ],
        ),
    ]
