# Generated by Django 4.1.3 on 2022-12-08 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0022_inventoryusage_id_alter_inventoryusage_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryusage',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
