# Generated by Django 4.1.3 on 2022-12-09 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0023_alter_inventoryusage_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="SalesPair",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "item_a",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_a",
                        to="storefront.menu",
                    ),
                ),
                (
                    "item_b",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_b",
                        to="storefront.menu",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="salespair",
            constraint=models.UniqueConstraint(
                fields=("item_a", "item_b"), name="a_b_unique"
            ),
        ),
    ]
