# Generated by Django 4.1.3 on 2022-12-09 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0025_salespair_amount_salespair_date"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salespair",
            name="a_b_unique",
        ),
        migrations.AddConstraint(
            model_name="salespair",
            constraint=models.UniqueConstraint(
                fields=("date", "item_a", "item_b"), name="a_b_unique"
            ),
        ),
    ]
