# Generated by Django 4.1.3 on 2022-12-09 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0026_remove_salespair_a_b_unique_salespair_a_b_unique"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="inventoryusage",
            constraint=models.UniqueConstraint(
                fields=("date", "item"), name="usage_unique"
            ),
        ),
    ]
