# Generated by Django 4.1.3 on 2022-12-11 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0028_itemcustomization_itemcustomization_single_cust"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="ingredient",
            constraint=models.UniqueConstraint(
                fields=("menu_item", "inventory"), name="unique_ingredients"
            ),
        ),
    ]
