# Generated by Django 4.1.3 on 2022-12-12 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("storefront", "0029_ingredient_unique_ingredients"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="salespair",
            name="a_b_unique",
        ),
        migrations.AddField(
            model_name="salespair",
            name="item_a_name",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="salespair",
            name="item_b_name",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name="salespair",
            constraint=models.UniqueConstraint(
                fields=("date", "item_a_name", "item_b_name"), name="a_b_unique"
            ),
        ),
    ]
